### ISSUE TITLE
[CSS][Página propiedad] Márgenes de cajas rosas

### ISSUE THREAD

**Issue by marilynpi** [marilynpi/jbsrur#34]
![captura de pantalla_2016-10-22_19-34-07](https://cloud.githubusercontent.com/assets/1868893/19622979/930c45b6-988e-11e6-9d93-cf8f4f892f0b.png)

**Comment by nercof** [comment]
Con incorporar va me parece:  `margin: 5px;` al sass  .referencia .div

![2016-12-06_15-12-04](https://cloud.githubusercontent.com/assets/10401452/20937787/35331f94-bbc7-11e6-8515-c560d123307f.png)

No me convence el tamaño de la letra, _deberíamos_ hacer que las cajas sean del mismo tamaño y que no se acomoden según la leyenda, ya que **Centro de atención** varia en la longitud de la Sucursal.

**Comment by nercof** [comment]
Solved with the Go-Live Activities
