### ISSUE TITLE
[Router] Navegación Propiedades

### ISSUE THREAD

**Issue by marilynpi** [marilynpi/jbsrur#35]
Pasos para reproducir:
1. Buscar propiedades con el buscador avanzado.
2. En la página de resultados, elegir una propiedad.
3. Volver atrás a la página de resultados.

![captura de pantalla_2016-10-22_19-41-22](https://cloud.githubusercontent.com/assets/1868893/19623010/8877a70c-988f-11e6-9125-d42d8a9b1bd2.png)

**Comment by nercof** [comment]
Se cierra el incidente. Con el correcto uso de $localStorage salvamos el inconveniente.

![paso1](https://cloud.githubusercontent.com/assets/10401452/19872903/dd1efb5e-9f9a-11e6-928b-7a99a65ad092.png)
![paso2](https://cloud.githubusercontent.com/assets/10401452/19872904/e0d867f8-9f9a-11e6-8d41-0dcc6e4d1c62.png)
![paso3](https://cloud.githubusercontent.com/assets/10401452/19872906/e11a2f4e-9f9a-11e6-887a-6edc2410db4b.png)
![paso4](https://cloud.githubusercontent.com/assets/10401452/19872905/e1174a4a-9f9a-11e6-90d8-b501f886b126.png)
